name: Tests

on: [push]

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Prepare Java"
        uses: "actions/setup-java@v3.0.0"
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Prepare Clojure CLI"
        uses: "DeLaGuardo/setup-clojure@master"
        with:
          cli: "latest"

      - name: "Apply Cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.m2/repository
          key: "contajners-${{ hashFiles('deps.edn') }}"
          restore-keys: "$contajners-"

      - name: Setup Babashka
        run: |
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          sudo bash install

      - name: "Run JVM tests"
        run: "clojure -M:test"

      - name: "Run bb tests"
        run: "bb bb-test.clj"
