name: Tests

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v5"

      - name: "Prepare Java"
        uses: "actions/setup-java@v5"
        with:
          distribution: "temurin"
          java-version: "24"

      - name: "Prepare Clojure"
        uses: "DeLaGuardo/setup-clojure@master"
        with:
          cli: "latest"
          bb: "latest"

      - name: "Apply Cache"
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.m2/repository
          key: "contajners-${{ hashFiles('deps.edn') }}"
          restore-keys: "$contajners-"

      - name: "Run JVM tests"
        run: "bb test:jvm"

      - name: "Run bb tests"
        run: "bb test:bb"
